apiVersion: apps/v1
kind: Deployment
metadata:
  name: producerapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producerapp
  template:
    metadata:
      labels:
        app: producerapp
    spec:
      containers:
        - name: producerapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}

